//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Component
{
    protected string name;
    public Component(string name)
    {
        this.name = name;
    }


	public virtual void Operation()
	{
		throw new System.NotImplementedException();
	}

    public abstract void Add(Component c);

    public abstract void Remove(Component c);


	public virtual void GetChild(int index)
	{
		throw new System.NotImplementedException();
	}

}

